// File generated by FlutterFire CLI for project autumn-chat-app-89fdf.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static bool get isConfigured {
    if (kIsWeb) {
      return false;
    }
    return defaultTargetPlatform == TargetPlatform.android ||
        defaultTargetPlatform == TargetPlatform.iOS;
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web — '
        're-run flutterfire configure with --platforms including web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb02XZ0EjxvZA-9hSPZcQc8qK-HsW7ZTM',
    appId: '1:895256964025:android:a029c0cf1a3c9e716ca468',
    messagingSenderId: '895256964025',
    projectId: 'autumn-chat-app-89fdf',
    storageBucket: 'autumn-chat-app-89fdf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQGBMNtuSuN4jR4Us3yqR9AZsULE3rlLo',
    appId: '1:895256964025:ios:dd0147850f446d8d6ca468',
    messagingSenderId: '895256964025',
    projectId: 'autumn-chat-app-89fdf',
    storageBucket: 'autumn-chat-app-89fdf.firebasestorage.app',
    iosBundleId: 'com.example.lovelyChatApp',
  );
}
